# Generated by Django 2.1.5 on 2019-11-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191127_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_certificated',
            field=models.BooleanField(default=True, verbose_name='인증여부'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
