# Generated by Django 2.1.5 on 2019-10-29 15:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191005_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='카테고리 이름')),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
