# Generated by Django 2.1.5 on 2019-12-03 11:57

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='닉네임')),
                ('firstname', models.CharField(blank=True, max_length=30, verbose_name='성')),
                ('lastname', models.CharField(blank=True, max_length=30, verbose_name='이름')),
                ('student_id', models.CharField(max_length=7, unique=True, verbose_name='학번')),
                ('major', models.CharField(max_length=200, verbose_name='주전공')),
                ('major_type', models.CharField(choices=[('주전공', '문헌정보학과'), ('복수전공', '타전공')], default='주전공', max_length=4, verbose_name='전공형태')),
                ('permission', models.CharField(choices=[('ADMIN', '관리자'), ('TINK', '팅커벨'), ('PETER', '일반')], default='PETER', max_length=2, verbose_name='권한')),
                ('certification_date', models.DateField(blank=True, default=None, null=True, verbose_name='인증일')),
                ('is_certificated', models.BooleanField(default=False, verbose_name='인증여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 권한')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용중')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
