# Generated by Django 2.1.5 on 2019-10-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
