# Generated by Django 2.1.5 on 2019-10-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pr_day',
            field=models.TextField(default='월, 화, 수, 목, 금'),
        ),
        migrations.AddField(
            model_name='board',
            name='pr_enddate',
            field=models.DateField(default='2019-08-31'),
        ),
        migrations.AddField(
            model_name='board',
            name='pr_endtime',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='board',
            name='pr_file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='pr_inst',
            field=models.CharField(default='도서관', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='pr_location',
            field=models.TextField(default='서울시'),
        ),
        migrations.AddField(
            model_name='board',
            name='pr_num',
            field=models.CharField(default='1명', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='pr_startdate',
            field=models.DateField(default='2019-07-01'),
        ),
        migrations.AddField(
            model_name='board',
            name='pr_starttime',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='board',
            name='pr_tranbus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='board',
            name='pr_transub',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
